FROM docker.io/library/tomcat:9.0.105-jdk11    

MAINTAINER "MINJUNG<wndtmgld5551@gmail.com>"

RUN rm -rf /usr/local/tomcat/webapps/

ADD mariadb-java-client-3.5.3.jar /usr/local/tomcat/lib/
ADD target/ohgoodfood-1.0.0-BUILD-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT.war
